# thanks to iirekm for articulating this: https://stackoverflow.com/a/59988803
name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:

  test-posix:
    # XXX: uncomment to disable
    if: false
    name: Build and test on Linux / macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
        with:
          tree-sitter-ref: v0.23.0
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Assemble the web directory
        run: NON_INTERACTIVE=1 sh build-and-run.sh
      - name: Test
        run: sh test.sh

  test-windows-mingw:
    # XXX: uncomment to disable
    #if: false
    name: Build and test on Windows (MinGW + Git for Windows)
    runs-on: windows-latest
    steps:
      # why isn't scoop included in the runner image?
      - name: Set up scoop
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          apps: mingw tree-sitter

      # why isn't this included in the runner image?
      - name: Make mingw binaries (gcc, make) available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/mingw/current/bin" >> $GITHUB_PATH

      - name: Make tree-sitter cli available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/tree-sitter/current/bin" >> $GITHUB_PATH

      # without the following, wsl seems to get triggered (at least
      # when using the runner image) when trying to execute `bash
      # script/build-wasm` within our code...it's very strange because
      # that particular bash.exe (the one under c:\windows\system32)
      # doesn't seem to get triggered elsewhere ("outside" of the
      # world within `sh build-and-run.sh` below, i.e. "up / out
      # here").  changing PATH in various ways did not have the
      # desirable effect.  so...how about removing the binary?  thanks
      # to Mizux: https://stackoverflow.com/a/69251820 for the idea.
      # now...how long will this keep working?
      - name: Remove wsl-triggering file
        shell: bash
        run: rm 'C:\windows\system32\bash.exe'
      # perhaps this could have been avoided if a good way to disable
      # wsl had been found.

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Assemble the web directory
        shell: bash
        run: NON_INTERACTIVE=1 sh build-and-run.sh

      - name: Output the current working directory name and content
        shell: bash
        run: pwd && ls -al

      - name: Save MinGW version of janet executable
        uses: actions/upload-artifact@v4
        with:
          name: mingw-janet
          path: .\janet\build\janet.exe

      - name: Test
        shell: bash
        run: sh test.sh

