name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:

  test-posix:
    # XXX: disable
    if: false
    name: Build and test on Linux / macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
        with:
          tree-sitter-ref: v0.23.0
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Assemble the web directory
        run: NON_INTERACTIVE=1 sh build-and-run.sh
      - name: Test
        run: sh test.sh

  test-windows-mingw:
    # XXX: disable job
    #if: false
    name: Build and test on Windows (MinGW)
    runs-on: windows-latest
    steps:
      - name: Which bash
        shell: bash
        run: which bash

      - name: Set up scoop
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          apps: mingw tree-sitter
#          apps: git mingw tree-sitter

#      - name: Make git-bash available
#        shell: bash
#        run: |
#          echo "$USERPROFILE/scoop/apps/git/current" >> $GITHUB_PATH

      - name: Which bash
        shell: bash
        run: which bash
      - name: Locate bash via cmd
        shell: cmd
        run: where bash
      - name: Locate bash via powershell
        shell: powershell
        run: where.exe bash

      - name: Make mingw binaries (gcc, make) available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/mingw/current/bin" >> $GITHUB_PATH

      - name: Make tree-sitter cli available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/tree-sitter/current/bin" >> $GITHUB_PATH

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Show PATH for bash
        shell: bash
        run: echo $PATH
      - name: Which bash
        shell: bash
        run: which bash
      - name: Locate bash via cmd (before)
        shell: cmd
        run: where bash
      - name: Locate bash via powershell (before)
        shell: powershell
        run: where.exe bash

      # without this, wsl seems to get triggered when trying to execute
      # bash script/build-wasm within our code...
      - name: Remove wsl-triggering file
        shell: bash
        run: rm 'C:\windows\system32\bash.exe'

      - name: Locate bash via cmd (after)
        shell: cmd
        run: where bash
      - name: Locate bash via powershell (after)
        shell: powershell
        run: where.exe bash

      - name: Assemble the web directory
        shell: bash
        run: NON_INTERACTIVE=1 sh build-and-run.sh

      - name: Test
        shell: bash
        run: sh test.sh

