name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:

  test-posix:
    # XXX: disable
    #if: false
    name: Build and test on Linux / macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
        with:
          tree-sitter-ref: v0.23.0
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Assemble the web directory
        run: NON_INTERACTIVE=1 sh build-and-run.sh
      - name: Test
        run: sh test.sh

  test-windows-mingw:
    # XXX: disable job
    if: false
    name: Build and test on Windows (MinGW)
    runs-on: windows-latest
    steps:
      - name: Which bash
        shell: bash
        run: which bash
      - name: Set up scoop
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          apps: mingw tree-sitter          
#          apps: git mingw tree-sitter
#      - name: Make git-bash available
#        shell: bash
#        run: |
#          echo "$USERPROFILE/scoop/apps/git/current" >> $GITHUB_PATH
#      - name: Which bash
#        shell: bash
#        run: which bash
      - name: Make mingw binaries (gcc, make) available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/mingw/current/bin" >> $GITHUB_PATH
      - name: Make tree-sitter cli available
        shell: bash
        run: |
          echo "$USERPROFILE/scoop/apps/tree-sitter/current/bin" >> $GITHUB_PATH
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Show PATH for bash
        shell: bash
        run: echo $PATH
      - name: Which bash
        shell: bash
        run: which bash
      - name: Assemble the web directory
        shell: bash
        # fails in script/build-wasm step -- failed to create process
        run: NON_INTERACTIVE=1 sh build-and-run.sh
      - name: Test
        shell: bash
        run: sh test.sh

